[package]
name = "egui_demo_app"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { version = "0.6.0", path = "../eframe"}
egui_demo_lib = { version = "0.6.0", path = "../egui_demo_lib"}
serde = { version = "1", features = ["derive"] }
