[package]
name = "egui"
version = "0.1.1"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Simple, portable immediate mode GUI library for Rust"
edition = "2018"
homepage = "https://github.com/emilk/emigui/"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/emilk/emigui"
categories = ["gui", "graphics"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [ "**/*.rs", "Cargo.toml", "fonts/ProggyClean.ttf", "fonts/Comfortaa-Regular.ttf"]

[lib]

[dependencies]
ahash = "0.3"
parking_lot = "0.10"
rusttype = "0.9"
serde = { version = "1", features = ["derive"], optional = true }

[features]
with_serde = ["serde"]

[dev-dependencies]
criterion = { version = "0.3", default-features = false }

[[bench]]
name = "benchmark"
harness = false
