[package]
name = "egui"
version = "0.5.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Simple, portable immediate mode GUI library for Rust"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "graphics"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [
  "**/*.rs",
  "Cargo.toml",
  "fonts/*.ttf",
]

[lib]

[dependencies]
ahash = { version = "0.6", features = ["std"], default-features = false }
atomic_refcell = { version = "0.1", optional = true } # Used instead of parking_lot when you are always using Egui in a single thread. About as fast as parking_lot.
parking_lot = { version = "0.11", optional = true } # Using parking_lot over std::sync::Mutex gives 50% speedups in some real-world scenarios
rusttype = "0.9"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
criterion = { version = "0.3", default-features = false }

[features]
default = ["atomic_refcell"]  # Using the same egui::Context from multiple threads will result in a panic.
multi_threaded = ["parking_lot"] # Only needed if you plan to use the same egui::Context from multiple threads.

[[bench]]
name = "benchmark"
harness = false
