[package]
name = "egui"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]

[dependencies]
ahash = "0.3"
parking_lot = "0.10"
rusttype = "0.9"
serde = { version = "1", features = ["derive"], optional = true }

[features]
with_serde = ["serde"]

[dev-dependencies]
criterion = { version = "0.3", default-features = false }

[[bench]]
name = "benchmark"
harness = false
