[package]
name = "egui_demo_lib"
version = "0.6.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Example library for Egui"
edition = "2018"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "graphics"]
keywords = ["glium", "egui", "gui", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[lib]

[dependencies]
egui = { version = "0.6.0", path = "../egui", features = ["serde"] }
epi = { version = "0.6.0", path = "../epi", features = ["serde", "serde_json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Http fetch app:
image = { version = "0.23", default_features = false, features = ["jpeg", "png"] }
syntect = { version = "4", default_features = false, features = ["default-fancy"] }

[dev-dependencies]
criterion = { version = "0.3", default-features = false }

[[bench]]
name = "benchmark"
harness = false
