[package]
name = "egui_glium"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
egui = { path = "../egui", features = ["with_serde"] }

chrono = { version = "0.4" }
clipboard = "0.5"
glium = "0.27"
serde_json = "1"
webbrowser = "0.5"
