[package]
name = "egui_glium"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
egui = { path = "../egui" }

chrono = { version = "0.4" }
clipboard = "0.5"
glium = "0.24"
serde_json = "1"
webbrowser = "0.5"
