[package]
name = "emigui"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
parking_lot = "0.10"
rusttype = "0.9"
serde = "1"
serde_derive = "1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
