[package]
name = "emigui"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
# palette = "0.4"
rusttype = "0.8"
serde = "1"
serde_derive = "1"
