[package]
name = "example_glium"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
egui = { path = "../egui" }
egui_glium = { path = "../egui_glium" }
serde = "1"
serde_derive = "1"
serde_json = "1"

glium = "0.24"
