[package]
name = "example_glium"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

[dependencies]
emigui = { path = "../emigui" }
emigui_glium = { path = "../emigui_glium" }

clipboard = "0.5"
glium = "0.24"
webbrowser = "0.5"
