[package]
name = "example_glium"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

[dependencies]
emigui = { path = "../emigui" }
emigui_glium = { path = "../emigui_glium" }
serde = "1"
serde_derive = "1"
serde_json = "1"

glium = "0.24"
