[package]
name = "egui_web"
version = "0.1.3"
authors = ["Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Bindings for compiling Egui code to WASM for a web page"
license = "MIT OR Apache-2.0"
edition = "2018"
homepage = "https://github.com/emilk/egui"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["gui", "graphics"]
keywords = ["wasm", "web", "egui", "gui", "gamedev"]
include = [ "**/*.rs", "Cargo.toml"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
egui = { version = "0.1.3", path = "../egui", features = ["serde"] }
js-sys = "0.3"
parking_lot = "0.11"
serde = "1"
serde_json = "1"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
  'console',
  'CssStyleDeclaration',
  'Document',
  'DomRect',
  'Element',
  'HtmlCanvasElement',
  'HtmlElement',
  'KeyboardEvent',
  'Location',
  'MouseEvent',
  'Performance',
  'Storage',
  'Touch',
  'TouchEvent',
  'TouchList',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlTexture',
  'WebGlUniformLocation',
  'WheelEvent',
  'Window',
]
