[package]
name = "emigui_glium"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

[dependencies]
emigui = { path = "../emigui" }

chrono = { version = "0.4" }
clipboard = "0.5"
glium = "0.24"
serde_json = "1"
webbrowser = "0.5"
